name: Mirror to GitLab

on:
  push:
    branches:
      - main  # Falls du weitere Branches spiegeln willst, füge sie hier hinzu.

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_ACCESS_TOKEN }}@gitlab.com/xe43nok/PlantProtectionSim.git
          git push --mirror gitlab
